openMF/ph-ee-integration-test

- src/main/java/org/mifos/integrationtest/config/ChannelConnectorConfig.java
- src/main/java/org/mifos/integrationtest/config/OperationsAppConfig.java
- src/main/resources/application.yaml
- src/test/java/org/mifos/integrationtest/ClientCorrelationIdTest.java
- src/test/java/org/mifos/integrationtest/common/Utils.java
- src/test/java/org/mifos/integrationtest/common/dto/operationsapp/TransactionRequest.java
- src/test/java/org/mifos/integrationtest/cucumber/BaseStepDef.java
- src/test/java/org/mifos/integrationtest/cucumber/ChannelClientIdDef.java
- src/test/java/org/mifos/integrationtest/cucumber/GetTxnApiDef.java
- src/test/java/resources/channelClientId.feature
- src/test/java/resources/getTransfer.feature
- src/test/java/resources/getTxn.feature
This contains integration tests for:
Transfers end point with client correlationid
Get Transaction req with client correlationid
Collection Req correlationId check
Channel txn state api to fetch txn by client correlation id from transfers table
Channel txn state api to fetch txn by client correlation id from txn req table
Also added flag for no auth ops app api testing
@danishjamal104 @fynmanoj
> Cucumber Integration test for Collection API and new channel API

- src/main/resources/application.yaml
- src/test/java/org/mifos/integrationtest/cucumber/AuthStepDef.java
- src/test/java/resources/channelClientId.feature
- src/test/java/resources/getTransfer.feature
- src/test/java/resources/getTxn.feature
Fix for:
Fix Integration Test for channel new api
Existing ops app step def to work with disable auth
> Updating integration tests

- src/main/resources/application.yaml
- changed channel url to https
@avikganguly01 @fynmanoj
> Changed channel to https

- src/test/java/org/mifos/integrationtest/common/dto/BatchApiResponseDTO.java
- src/test/java/org/mifos/integrationtest/common/dto/loan/LoanAccountData.java
- src/test/java/org/mifos/integrationtest/common/dto/loan/LoanProduct.java
- resolved getters and setters issue
@avikganguly01 @fynmanoj
> Resolved getters and setters issue

- src/test/java/org/mifos/integrationtest/common/HttpMethod.java
- src/test/java/org/mifos/integrationtest/config/MockServer.java
- src/test/java/org/mifos/integrationtest/config/MockServerConfig.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/MockServerStepDef.java
- src/test/java/resources/mockserver.feature
1. New scenario implemented `Mockserver stub test` under `mockserver.feature`.
2. This test case will test the working of mockserver.
Refer jira ticket >> [PHEE-238](https://fynarfin.atlassian.net/browse/PHEE-238)
[PHEE-238]: https://fynarfin.atlassian.net/browse/PHEE-238?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Done PHEE-238 Added test case for mockserver stub

- src/test/java/org/mifos/integrationtest/cucumber/stepdef/GetTxnApiDef.java
- src/test/java/resources/getTxn.feature
Adding test to determine dateformat output for a collection request (fetched by Get txn req api)
> Adding integ test for dateformat

- src/test/java/org/mifos/integrationtest/cucumber/stepdef/BatchApiStepDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/MockFlowTestDef.java
- src/test/java/resources/mockFlowTest.feature
Updating test case for [GOV-463](https://mifosforge.jira.com/browse/GOV-463)
New test case for: [GOV-338](https://mifosforge.jira.com/browse/GOV-338) 
[GOV-463]: https://mifosforge.jira.com/browse/GOV-463?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[GOV-338]: https://mifosforge.jira.com/browse/GOV-338?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GOV-338: Integration test updation and new test case

- src/test/java/org/mifos/integrationtest/cucumber/stepdef/BatchApiStepDef.java
- src/test/java/resources/batch.feature
Test for : https://github.com/openMF/ph-ee-bulk-processor/pull/51
> Suggested Callback Time that is Resolved by Polling

- src/test/java/org/mifos/integrationtest/cucumber/stepdef/PaybillApiStepDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/PaybillStepDef.java
- src/test/java/resources/paybill.feature
- Fixed Paybill Integration Tests
- Proper class names for step def
@fynmanoj
> Paybill integration test

- src/test/java/org/mifos/integrationtest/common/dto/loan/LoanAccountData.java
- src/test/java/org/mifos/integrationtest/common/dto/loan/LoanProduct.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/GSMATransferDef.java
- temporary fix for passing integration tests for loan account
- changed dtos
@fynmanoj @avikganguly01
> Fixed the tests and dto change

- src/test/java/resources/batch.feature
Refer this issue for more info [PHEE-297](https://fynarfin.atlassian.net/browse/PHEE-297)
[PHEE-297]: https://fynarfin.atlassian.net/browse/PHEE-297?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix PHEE-297 Batch test bug fixed

- src/main/java/org/mifos/integrationtest/config/BulkProcessorConfig.java
- src/main/resources/application.yaml
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/BaseStepDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/BatchApiStepDef.java
- src/test/java/resources/batch.feature
Related PRs: https://github.com/openMF/ph-ee-env-labs/pull/29
https://github.com/openMF/ph-ee-bulk-processor/pull/48
> Adding integration test for callback

- build.gradle
- src/main/resources/application.yaml
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/BaseStepDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/IdentityMapperStepDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/MockServerStepDef.java
- src/test/java/resources/identityMapperTest.feature
- src/test/java/resources/ph-ee-bulk-demo-7.csv
Integration Test for Identity Account Mapper
[GOV-320](https://mifosforge.jira.com/browse/GOV-320)
[GOV-320]: https://mifosforge.jira.com/browse/GOV-320?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Identity Account Mapper Test

- src/main/java/org/mifos/integrationtest/config/GsmaConfig.java
- src/main/resources/application.yaml
- src/test/java/org/mifos/integrationtest/common/dto/savings/InteropIdentifier.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/GSMATransferDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/GSMATransferStepDef.java
- src/test/java/resources/gsmaTxn.feature
[PHEE-315](https://fynarfin.atlassian.net/browse/PHEE-315)
[PHEE-315]: https://fynarfin.atlassian.net/browse/PHEE-315?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PHEE-315: GSMA transfer API integration test is not working.

- src/main/java/org/mifos/integrationtest/config/BulkProcessorConfig.java
- src/main/resources/application.yaml
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/BaseStepDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/BatchApiStepDef.java
- src/test/java/resources/batch.feature
[PHEE-314](https://fynarfin.atlassian.net/browse/PHEE-314?atlOrigin=eyJpIjoiM2Y3ZDY0OTMyYTZhNGJlYWIxZWYzOGZiZjZjMGRlOGIiLCJwIjoiamlyYS1zbGFjay1pbnQifQ): Fixed phased callback integ test 
[PHEE-314]: https://fynarfin.atlassian.net/browse/PHEE-314?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PHEE-314 Fixed phased callback integ test

- src/test/java/resources/mockFlowTest.feature
- src/test/java/resources/mockserver.feature
[PHEE 343 Removing the mistakenly rebased and addded case](https://fynarfin.atlassian.net/browse/PHEE-343)
[This PR is the one which Ankita wrote](https://github.com/openMF/ph-ee-integration-test/commit/96c4624f1a3cda33df4abe478d4adfac0274985a#diff-928b0e8bd4c3117d8f3f334917b883e931f548919ddc2329c8f8e2fd3b08452f)
> PHEE 343 fix minimal mock fund transfer flow test case

- src/test/java/org/mifos/integrationtest/ClientCorrelationIdTest.java
- src/test/java/org/mifos/integrationtest/ExternalIdTest.java
- src/test/java/resources/jsonWebSignature.feature
* [Disabled the junit test cases](https://fynarfin.atlassian.net/browse/PHEE-351)
> PHEE-351 Disabled the junit test cases

- src/test/java/resources/mockFlowTest.feature
- src/test/java/resources/validateTxn.feature
* [Updated the tag for the passing test](https://fynarfin.atlassian.net/browse/PHEE-351)
> PHEE-351 Updated the tag for the passing test

- src/test/java/resources/mockFlowTest.feature
- src/test/java/resources/validateTxn.feature
* [Adding govtodo tag to failing cases](https://fynarfin.atlassian.net/browse/PHEE-351)
> PHEE-351 Adding govtodo tag to failing cases

- .circleci/config.yml
[PHEE-355 Add script to circle ci config to run @amsIntegration](https://fynarfin.atlassian.net/browse/PHEE-355?atlOrigin=eyJpIjoiZTVkYWJhNWExN2E2NDc1Mjg3ZWVmYWQ2NWQ2ZWY3ODMiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> PHEE-355 Add script to circle ci config to run @amsIntegration

- src/test/java/resources/gsmaTxn.feature
[PHEE-353 AMS integration test stability](https://fynarfin.atlassian.net/browse/PHEE-353?atlOrigin=eyJpIjoiNGE5NTQ2YTZhY2JhNGQ3MGJjNTQzZGE2ZDE0ZmU2NzkiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> Updating @amsIntegration tag to gsma txn test case

- src/test/java/org/mifos/integrationtest/cucumber/stepdef/MockFlowTestDef.java
- src/test/java/resources/mockFlowTest.feature
- [PHEE-357 Fix Mock fund flow transfer test](https://fynarfin.atlassian.net/browse/PHEE-357?atlOrigin=eyJpIjoiMGYwYjhkNjBjZTFhNGZmYmIzYTVlYzkyZTYzZGM5YzYiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> PHEE- 357 Fixing typo of PayerDfspId in mock flow test

- src/test/java/resources/mockFlowTest.feature
- [PHEE-357 Fix Mock fund flow transfer test](https://fynarfin.atlassian.net/browse/PHEE-357?atlOrigin=eyJpIjoiMDBlNGE1MGViYmZmNGM5MjhmNzE3MDExN2ZmZjdjNDciLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> PHEE-357 Marking mock fund transfer case as TODO

- .circleci/config.yml
parameterized region for new cluster
Jira Ticket : https://fynarfin.atlassian.net/browse/PHEE-346?atlOrigin=eyJpIjoiY2RhMGRiNzRiYmZhNDcwY2IxMDNmMzhlZWQwYjQ2MjkiLCJwIjoiamlyYS1zbGFjay1pbnQifQ
> PHEE- 346 : Update config.yml for region params

- .circleci/config.yml
- Added localtunnel to expose the wiremock server
https://fynarfin.atlassian.net/browse/PHEE-380?atlOrigin=eyJpIjoiZjI4YTQxNTZjODAyNDlkMGE0MDc5MmNiNmI2NTY2MzQiLCJwIjoiamlyYS1zbGFjay1pbnQifQ
> [PHEE-380] Added localtunnel to expose the wiremock server

- src/test/java/resources/mockFlowTest.feature
Changing tag for minimally mock fund TC 
> Changing minimally mock fund TC to @gov

- src/test/java/resources/batch.feature
Marked  Batch Phased Callback Failure TC as to do
> Marking flaky test as to do

- .circleci/config.yml
- src/main/java/org/mifos/integrationtest/config/IdentityMapperConfig.java
- src/main/resources/application.yaml
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/IdentityMapperStepDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/MockServerStepDef.java
- src/test/java/resources/identityMapperTest.feature
- src/test/java/resources/inbound.feature
[GOV-517](https://mifosforge.jira.com/browse/GOV-517?atlOrigin=eyJpIjoiM2UxNWFlN2ZjN2U4NDVjMzg5OGZjZWMxZDE2ZWJmMDEiLCJwIjoiaiJ9)
[GOV-517]: https://mifosforge.jira.com/browse/GOV-517?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[GOV-362](https://mifosforge.jira.com/browse/GOV-362?atlOrigin=eyJpIjoiNzM2NDEwZWFhNDFhNGE1OGIxYWU4OTIwMzk2MTU1YzQiLCJwIjoiaiJ9)
[GOV-362]: https://mifosforge.jira.com/browse/GOV-362?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GOV-517 API guidelines changes

- src/test/java/resources/batch.feature
Changed related to design points in [GOV-78](https://mifosforge.jira.com/browse/GOV-78)
[GOV-78]: https://mifosforge.jira.com/browse/GOV-78?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GOV-78: Ability for the government to make a payment to an individual with a MoMo account 

- .circleci/config.yml
> recreate-pods-while-upgrage

- .circleci/config.yml
> Rename job steps

- .circleci/config.yml
- src/main/resources/application.yaml
(https://mifosforge.jira.com/browse/GOV-527) 
Description-
* Added steps to build image and push to the Docker hub through CircleCI.
* It checks for any new tag release and also builds images for the latest.
> #GOV-527 Image build and push to Dockerhub

- src/main/resources/application.yaml
* Fixes the bug introduced in #115 .
> Bulk contact point changed to ingress, instead of service name

- .circleci/config.yml
* Fixed circle ci bug introduced in #115 
> Reverted circle ci bug introduced in #115

- .circleci/config.yml
> ngrok-config-updated-for-test-case

- src/test/java/org/mifos/integrationtest/cucumber/stepdef/IdentityMapperStepDef.java
- src/test/java/resources/identityMapperTest.feature
* Identity Account Mapper Integration Test. [GOV-362](https://mifosforge.jira.com/browse/GOV-362?atlOrigin=eyJpIjoiZmIwY2VlOTMxNzRkNDgyZjhiZmFhMTFjZGRlYzJhNWYiLCJwIjoiaiJ9)
[GOV-362]: https://mifosforge.jira.com/browse/GOV-362?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GOV-362 Identity Account Mapper Test

- src/test/java/org/mifos/integrationtest/cucumber/stepdef/BatchApiStepDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/MockFlowTestDef.java
- src/test/java/resources/batch_demo_csv/ph-ee-bulk-demo-7.csv
- src/test/java/resources/mockFlowTest.feature
Includes integration  test for batch processing with minimal mock fund transfer. Verifies the total txn count being equal to success txn count.
Needs : https://github.com/openMF/ph-ee-operations-app/pull/67 to be merged
> Bulk with txn count and success count

- src/test/java/org/mifos/integrationtest/cucumber/stepdef/GSMATransferStepDef.java
- src/test/java/resources/identityMapperTest.feature
* [GOV-364](https://mifosforge.jira.com/browse/GOV-364?atlOrigin=eyJpIjoiNDQwM2IwZjkzZTM5NDhkYThlNzMzYmJiZDQ2YmRmOWUiLCJwIjoiaiJ9)
[GOV-364]: https://mifosforge.jira.com/browse/GOV-364?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GOV-364 AMS Integration

- src/main/java/org/mifos/integrationtest/config/VoucherManagementConfig.java
- src/main/resources/application.yaml
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/BaseStepDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/VoucherManagementStepDef.java
- src/test/java/resources/voucherManagementTest.feature
* [GOV-313](https://mifosforge.jira.com/browse/GOV-313?atlOrigin=eyJpIjoiZGRmZTQxNzU3ODUyNDVlOThkNWE2MzZkYzMxOTBmZGMiLCJwIjoiaiJ9)
[GOV-313]: https://mifosforge.jira.com/browse/GOV-313?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GOV-313 Voucher Integration Test

- src/test/java/org/mifos/integrationtest/common/CollectionHelper.java
- src/test/java/org/mifos/integrationtest/common/dto/operationsapp/GetTransactionRequestResponse.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/BaseStepDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/ChannelCollectionStepDef.java
- src/test/java/resources/channelCollection.feature
[PHEE-408 Channel Collection api config update integration test](https://fynarfin.atlassian.net/browse/PHEE-408?atlOrigin=eyJpIjoiMjk4ZjEyOTViZDI0NDZkOTlhYzBlNDYxZmE2OTlhMjciLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
depends on: https://github.com/openMF/ph-ee-connector-channel/pull/128
[PHEE-422 Create minimalMockTransferRequest BPMN, its workers, required configurations, integration test](https://fynarfin.atlassian.net/browse/PHEE-422?atlOrigin=eyJpIjoiOGZlZTE1MTBjOGVmNDhjMTg3ODEyMWI5MjU2M2NiNDAiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
depends on: 
https://github.com/openMF/ph-ee-env-labs/pull/170
https://github.com/openMF/ph-ee-connector-mock-payment-schema/pull/18
https://github.com/openMF/ph-ee-connector-channel/pull/137
https://github.com/openMF/ph-ee-importer-rdbms/pull/66
Please make sure these boxes …
> PHEE-408 Channel Collection api config update integration test

- src/test/java/org/mifos/integrationtest/common/dto/BatchRequestDTO.java
- src/test/java/org/mifos/integrationtest/common/dto/Party.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/BaseStepDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/BatchApiStepDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/JWSStepDef.java
- src/test/java/resources/batch.feature
* Added test case for the batch transaction rest based api
* Modified step `I generate signature`,  for generating the signature for both json payload and file based payload.
* New test case `BD-012 Batch Transaction REST Api test`.
* Includes the latest assertion design for bulk.(Asserting if totalTxnCount == successTxnCount)
[PHEE-415](https://fynarfin.atlassian.net/browse/PHEE-415)
[PHEE-415]: https://fynarfin.atlassian.net/browse/PHEE-415?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PHEE-415: Added test case for the batch rest json based api

- src/main/java/org/mifos/integrationtest/config/VoucherManagementConfig.java
- src/main/resources/application.yaml
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/VoucherManagementStepDef.java
- src/test/java/resources/voucherManagementTest.feature
> GOV-105 Fetch Api test

- src/test/java/org/mifos/integrationtest/common/dto/BatchRequestDTO.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/BatchApiStepDef.java
- src/test/java/resources/batch.feature
- src/test/java/resources/mockFlowTest.feature
Integration test updated for https://github.com/openMF/ph-ee-bulk-processor/pull/119
> GOV-556:API compliance

- src/main/java/org/mifos/integrationtest/config/NetflixConductorConfig.java
- src/main/java/org/mifos/integrationtest/config/OperationsAppConfig.java
- src/main/resources/application.yaml
- src/test/java/org/mifos/integrationtest/common/TransferHelper.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/BaseStepDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/GSMATransferStepDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/NCStepDef.java
- src/test/java/resources/netflixConductor.feature
https://mifosforge.jira.com/browse/G2PCCODV-213
> G2PCCODV-213  Setup Netflix Conductor

- src/test/java/org/mifos/integrationtest/cucumber/stepdef/BaseStepDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/GSMATransferStepDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/InboundStepDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/MockFlowTestDef.java
- src/test/java/resources/mockFlowTest.feature
> GOV-517 Minimal mock fund transfer with account lookup test

- build.gradle
- src/main/java/org/mifos/integrationtest/config/KeycloakConfig.java
- src/main/java/org/mifos/integrationtest/config/KongConfig.java
- src/main/java/org/mifos/integrationtest/config/KongOidcPluginConfig.java
- src/main/resources/application.yaml
- src/test/java/org/mifos/integrationtest/common/dto/KeycloakTokenResponse.java
- src/test/java/org/mifos/integrationtest/common/dto/kong/Access.java
- src/test/java/org/mifos/integrationtest/common/dto/kong/KeycloakUpdateRequest.java
- src/test/java/org/mifos/integrationtest/common/dto/kong/KeycloakUser.java
- src/test/java/org/mifos/integrationtest/common/dto/kong/KongService.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/AuthStepDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/BaseStepDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/InboundStepDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/KeycloakStepDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/KongStepDef.java
- src/test/java/resources/authentication.feature
Updates in this PR
1. Added test case `Unauthorized channel-connector test`.
2. Added test case `Authorized channel-connector test`.
3. Disabled junit test cases which we are not maintaining.
> GOV 287.3 Test cases added for channel-connector auth test

- build.gradle
- src/main/resources/application.yaml
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/BaseStepDef.java
* Updated the versino of connector-common to `1.7.1-rc.1`.
* Simplified the underlying definition of step `I generate signature`, using the `JsonWebSignatureBuilder`.
[PHEE-479](https://fynarfin.atlassian.net/browse/PHEE-479)
[PHEE-479]: https://fynarfin.atlassian.net/browse/PHEE-479?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PHEE-479: Updated the generate signature underlying code with simpler version

- .circleci/config.yml
[PHEE-490 Publish helm chart with jira ticket from circleci](https://fynarfin.atlassian.net/browse/PHEE-490?atlOrigin=eyJpIjoiMDAwNWMwNjNmN2NhNGUyZWExZDU4NWIwNGU3MmU5ZjUiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> [PHEE-490] Publish helm chart with jira ticket from circleci

- src/main/java/org/mifos/integrationtest/config/MojaloopConfig.java
- src/main/java/org/mifos/integrationtest/config/OperationsAppConfig.java
- src/main/java/org/mifos/integrationtest/config/PayerFundTransferConfig.java
- src/main/resources/application.yaml
- src/test/java/org/mifos/integrationtest/common/TransferHelper.java
- src/test/java/org/mifos/integrationtest/common/dto/mojaloop/AddUserAlsRequest.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/BaseStepDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/GSMATransferStepDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/MockServerStepDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/MojaloopDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/MojaloopStepDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/PayerFundTransferDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/PayerFundTransferStepDef.java
- src/test/java/resources/mojaloop.feature
[PHEE-496 Update ml-connector config](https://fynarfin.atlassian.net/browse/PHEE-496?atlOrigin=eyJpIjoiZTIzZTY5ODA2N2Y1NDAyY2JhZDU3YWJjOTkwODkxNjQiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
[PHEE-488 add callback url option in ml connector for lookup, quotation and transfer](https://fynarfin.atlassian.net/browse/PHEE-488?atlOrigin=eyJpIjoiYzlkZTQ1MDA0YzFiNDhjNGI3MDMyZTA3OWE2ZWFlNjEiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
[PHEE-495 disable non required services in mojaloop-v15.1.0](https://fynarfin.atlassian.net/browse/PHEE-495?atlOrigin=eyJpIjoiMzVhMjI3OTIyMTEyNGRlZDgwZjY2ZTMxZGE1NjJkNDYiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
FYI our guidelines for code reviews same as https://cwiki.apache.org/confluence/display/FINERACT/Code+Rev …
> [PHEE-496] Update ml-connector config

- src/test/java/resources/authentication.feature
- src/test/java/resources/batch.feature
- src/test/java/resources/identityMapperTest.feature
- src/test/java/resources/mockFlowTest.feature
- src/test/java/resources/operationsBatch.feature
[PHEE-502 Fix integration test for v1.11.0 release.](https://fynarfin.atlassian.net/browse/PHEE-502?atlOrigin=eyJpIjoiZmY2NTg0ODEwOWE2NDY4ZGIyMmU2MmMwZGY3ZDBmOGQiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> [PHEE-502] Fix integration test for v1.11.0 release.

- build.gradle
- src/main/resources/application.yaml
(https://fynarfin.atlassian.net/browse/PHEE-485)
* Added a test scenario on the name specific to test run a single test case.
> PHEE-485 Single test scenario 

- .circleci/config.yml
- build.gradle
> [PHEE-516] update-test-with-start-up-test

- .circleci/config.yml
- src/main/java/org/mifos/integrationtest/config/ChannelConnectorConfig.java
- src/main/resources/application.yaml
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/BaseStepDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/ErrorCodeStepDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/GSMATransferStepDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/KeycloakStepDef.java
- src/test/java/resources/gsmaP2P.feature
Int test for batch with gsma p2p
related Prs : https://github.com/openMF/ph-ee-connector-channel/pull/139
> [GOV-78] P2P w/o batch

- .circleci/config.yml
- src/main/resources/application.yaml
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/GSMATransferStepDef.java
> [GOV-78] Fix for ML TC regressions

- .circleci/config.yml
[PHEE-520 Wrong chart is used by orb in integration test repo](https://fynarfin.atlassian.net/browse/PHEE-520?atlOrigin=eyJpIjoiOTdhMGRkYWQ4MDQ4NDg3YmFkNjc5YzVhMjQ0NmE0OGIiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> [PHEE-520] Wrong chart is used by orb in integration test repo

- src/test/java/org/mifos/integrationtest/cucumber/stepdef/KongStepDef.java
- src/test/java/resources/kongSecurity.feature
Rate limiting implemetation for [GOV-410](https://mifosforge.jira.com/browse/GOV-410)
Updated the tag to :   @GOV-410 to disable this tc
SS:
[GOV-410]: https://mifosforge.jira.com/browse/GOV-410?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [GOV-410] API Gateway capabilities (Kong) - Observability

- src/test/java/org/mifos/integrationtest/cucumber/stepdef/BatchApiStepDef.java
- src/test/java/resources/batch.feature
> [PHEE-522] Callback sync int test

- src/test/java/org/mifos/integrationtest/cucumber/stepdef/BatchApiStepDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/BillPayStepDef.java
- src/test/java/resources/batch.feature
- src/test/java/resources/billPay.feature
> [GOV-83] Fix for P2G wiremock

- src/test/java/org/mifos/integrationtest/common/dto/operationsapp/BatchDTO.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/BatchApiStepDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/IdentityMapperStepDef.java
- src/test/java/resources/batch_demo_csv/ph-ee-bulk-demo-7.csv
- src/test/java/resources/identityMapperTest.feature
> [GOV-324] Integration Test

- src/test/java/org/mifos/integrationtest/cucumber/stepdef/VoucherManagementStepDef.java
- src/test/java/resources/voucherManagementTest.feature
> [PHEE-523] Voucher Test Fix

- src/test/java/resources/batch.feature
> [GOV-324] Tenant change for bulk api

- src/test/java/org/mifos/integrationtest/cucumber/stepdef/BillPayStepDef.java
> [GOV-83] Fix for BI-001

- build.gradle
- src/test/java/org/mifos/integrationtest/common/CsvHelper.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/PayerFundTransferStepDef.java
- src/test/java/resources/batch_demo_csv/batchTransaction.csv
- src/test/java/resources/mojaloop.feature
[PHEE-532 Test Batch transfer with Mojaloop](https://fynarfin.atlassian.net/browse/PHEE-532?atlOrigin=eyJpIjoiZTc4MDdiODQzMTYyNGE0ZGFmMGVkNGM5ZGUyNmM4YzciLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> [PHEE-532] Test Batch transfer with Mojaloop

- src/test/java/org/mifos/integrationtest/common/dto/billpayp2g/BillPaymentsReqDTO.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/BillPayStepDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/ScenarioScopeState.java
- src/test/java/resources/billPay.feature
Added TC for bill inquiry negative scenarios
> [GOV-83] Added TC for P2G negative scenarios

- .circleci/config.yml
- build.gradle
- src/main/resources/application.yaml
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/BaseStepDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/BatchApiStepDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/BulkPaymentStepDef.java
- src/test/java/resources/batch_demo_csv/bulk_payment.csv
- src/test/java/resources/bulkPayment.feature
* https://fynarfin.atlassian.net/browse/PHEE-552?atlOrigin=eyJpIjoiMTg0ZmJiNzQzODU2NGM2MmI3ZjUzNjQ2NmNkMTkwZDYiLCJwIjoiamlyYS1zbGFjay1pbnQifQ
> [PHEE-552]

- src/test/java/org/mifos/integrationtest/common/dto/BillRTPReqDTO.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/BillPayStepDef.java
- src/test/java/resources/billPay.feature
> [GOV-83] P2G RTP Negative Tests

- src/test/java/org/mifos/integrationtest/cucumber/stepdef/ChannelClientIdDef.java
- src/test/java/resources/channelClientId.feature
[PHEE-542 Convert get-txnState-correlationId Camel route to spring in Channel](https://fynarfin.atlassian.net/browse/PHEE-542?atlOrigin=eyJpIjoiYTEwMzQ0ZWQwOTk0NDQ2NmE1MTVlNTBiM2U2NDcwNjgiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> [PHEE-542] Integration Test for Channel Get Txn by Client Id API

- src/test/java/resources/identityMapperTest.feature
> [gov] callback url change

- src/test/java/org/mifos/integrationtest/cucumber/stepdef/BatchApiStepDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/GSMATransferStepDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/PayerFundTransferStepDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/ScenarioScopeState.java
- src/test/java/resources/gsmaP2P.feature
- src/test/java/resources/mojaloop.feature
> [GOV-78] TC for GSMA P2P with Batch

- .circleci/config.yml
- src/main/java/org/mifos/integrationtest/config/TenantConfig.java
- src/main/resources/application.yaml
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/BaseStepDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/GSMATransferStepDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/GenericStepDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/ScenarioScopeState.java
- src/test/java/resources/authentication.feature
- src/test/java/resources/batch.feature
- src/test/java/resources/billPay.feature
- src/test/java/resources/bulkPayment.feature
- src/test/java/resources/channelClientId.feature
- src/test/java/resources/getTransfer.feature
- src/test/java/resources/gsmaP2P.feature
- src/test/java/resources/identityMapperTest.feature
- src/test/java/resources/interopErrorCode.feature
- src/test/java/resources/jsonWebSignature.feature
- src/test/java/resources/mockFlowTest.feature
- src/test/java/resources/operationsBatch.feature
- src/test/java/resources/validationErrorCode.feature
> [PHEE-568] Configure tenants

- .circleci/config.yml
- src/main/resources/application.yaml
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/BaseStepDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/GSMATransferStepDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/GenericStepDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/ScenarioScopeState.java
- src/test/java/resources/batch_demo_csv/batchTransactionGsma.csv
- src/test/java/resources/gsmaP2P.feature
- src/test/java/resources/gsmaTxn.feature
- src/test/java/resources/identityMapperTest.feature
- src/test/java/resources/mockFlowTest.feature
- src/test/java/resources/netflixConductor.feature
> [PHEE-580] Update fineract FSP ids in intergation test

- src/test/java/org/mifos/integrationtest/cucumber/stepdef/BillPayStepDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/InboundStepDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/MockFlowTestDef.java
- src/test/java/resources/authentication.feature
- src/test/java/resources/mockFlowTest.feature
> [PHEE-592] Optimize time taken by GOV test cases

- src/test/java/resources/voucherManagementTest.feature
> [PHEE-595] Update the identifiers as prefix for the TCs

- src/main/resources/application.yaml
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/PayerFundTransferStepDef.java
- src/test/java/resources/gsmaP2P.feature
- src/test/java/resources/mojaloop.feature
[PHEE-594 fix mojaloop testcases](https://fynarfin.atlassian.net/browse/PHEE-594?atlOrigin=eyJpIjoiMjlkMjBiNGY3NmNlNDk2NGJjY2Q0YWU0ZDBjMDJmOWUiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> [PHEE-594] fix mojaloop testcases

- .circleci/config.yml
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/InboundStepDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/MockFlowTestDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/VoucherManagementStepDef.java
- src/test/java/resources/voucherManagementTest.feature
[PHEE-510 Validation for Voucher Lifecycle Management](https://fynarfin.atlassian.net/browse/PHEE-510?atlOrigin=eyJpIjoiYWMyNWM2ZmY4MjNiNGZhZjgxMDU3NTE1YmZmOWJhNTciLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> [PHEE-510] Integration test for Voucher Lifecycle Management APIs

- src/test/java/org/mifos/integrationtest/cucumber/stepdef/GSMATransferStepDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/IdentityMapperStepDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/ScenarioScopeState.java
- src/test/java/resources/batch_demo_csv/ph-ee-bulk-demo-7.csv
- src/test/java/resources/identityMapperTest.feature
> [GOV-60] IAM Test case

- src/test/java/org/mifos/integrationtest/cucumber/stepdef/GSMATransferStepDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/PayerFundTransferStepDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/ScenarioScopeState.java
- src/test/java/resources/batch_demo_csv/batchTransactionGsma.csv
- src/test/java/resources/gsmaP2P.feature
> [GOV-78a] Batch with different payers

- .circleci/config.yml
(https://fynarfin.atlassian.net/browse/PHEE-606)
- This job was rejected because the image is unavailable.(20.10.14)
- Updated with new version 20.10.24
> [PHEE-606] Update Docker Image for CircleCI Build

- .gitignore
- src/main/resources/application.yaml
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/BaseStepDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/ScenarioScopeState.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/VoucherManagementStepDef.java
- src/test/java/resources/voucherManagementTest.feature
[PHEE-597 Automate create and activate voucher step in integration test.](https://fynarfin.atlassian.net/browse/PHEE-597?atlOrigin=eyJpIjoiOGEyZjhhNDcxMTc3NDkwNjkyMGE1ZTkxMTZmOWEwOWIiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> [PHEE-597] Automate create and activate voucher step in integration test.

- src/test/java/org/mifos/integrationtest/cucumber/stepdef/VoucherManagementStepDef.java
https://fynarfin.atlassian.net/browse/PHEE-597
> [phee-597]integration test build fix

- src/test/java/org/mifos/integrationtest/cucumber/stepdef/BatchApiStepDef.java
- src/test/java/resources/batch.feature
- src/test/java/resources/batch_demo_csv/ph-ee-bulk-demo-6.csv
- src/test/java/resources/mockFlowTest.feature
> [PHEE-614]Change payment mode

- src/test/java/org/mifos/integrationtest/cucumber/stepdef/ScenarioScopeState.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/VoucherManagementStepDef.java
- src/test/java/resources/voucherManagementTest.feature
> [PHEE-614] Voucher test fix

- src/test/java/resources/batch.feature
> [PHEE-614] batch fix

- src/test/java/org/mifos/integrationtest/common/dto/BatchRequestDTO.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/BatchApiStepDef.java
[PHEE-634 batch transaction API request body as per API spec in documentation](https://fynarfin.atlassian.net/browse/PHEE-634?atlOrigin=eyJpIjoiY2EwZTI5ZWU1NTMyNDVlMjhhN2FkN2ZhMGM5NzUwMjkiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> [PHEE-634] batch transaction API request body as per API spec in documentation

- src/test/java/org/mifos/integrationtest/cucumber/stepdef/BillPayStepDef.java
- src/test/java/resources/billPay.feature
> [GOV-83A] Changes for new tc

- src/test/java/org/mifos/integrationtest/cucumber/stepdef/BillPayStepDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/GetTxnApiDef.java
- src/test/java/resources/getTxn.feature
[PHEE-635 Fix GTX-001 and GTX-002 integration test.](https://fynarfin.atlassian.net/browse/PHEE-635?atlOrigin=eyJpIjoiYzFkYmQyNTgzOTMzNGFmY2EwYTQwMDk5ZWI1ZGI0ZWIiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> [PHEE-635] Fix GTX-001 and GTX-002 integration test.

- src/test/java/org/mifos/integrationtest/cucumber/stepdef/ErrorCodeStepDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/GetTxnApiDef.java
[PHEE-635 Fix GTX-001 and GTX-002 integration test.](https://fynarfin.atlassian.net/browse/PHEE-635?atlOrigin=eyJpIjoiYzFkYmQyNTgzOTMzNGFmY2EwYTQwMDk5ZWI1ZGI0ZWIiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> [PHEE-635] Fix GTX-001 and GTX-002 integration test fix by adding await

- src/test/java/org/mifos/integrationtest/cucumber/stepdef/BatchApiStepDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/BillPayStepDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/ErrorCodeStepDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/GetTxnApiDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/ScenarioScopeState.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/VoucherManagementStepDef.java
- src/test/java/resources/batch.feature
- src/test/java/resources/batch_demo_csv/ph-ee-bulk-demo-6.csv
- src/test/java/resources/billPay.feature
- src/test/java/resources/bulkPayment.feature
- src/test/java/resources/getTxn.feature
- src/test/java/resources/identityMapperTest.feature
- src/test/java/resources/mockFlowTest.feature
- src/test/java/resources/operationsBatch.feature
- src/test/java/resources/validateTxn.feature
- src/test/java/resources/voucherManagementTest.feature
> V1.6.0 release- merge bck to release

- .circleci/config.yml
- src/test/java/resources/batch.feature
[PHEE-644 Bulk payments TC with some beneficiaries having invalid amout](https://fynarfin.atlassian.net/browse/PHEE-644?atlOrigin=eyJpIjoiN2VhYzVjYzllYzViNGFkMjkxYjQzMjJjYjVkNjJiODAiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> [PHEE-644] Bulk payments TC with all beneficiaries successfully receiving payment

- build.gradle
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/BatchApiStepDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/ErrorCodeStepDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/GSMATransferStepDef.java
- src/test/java/resources/batch.feature
[PHEE-648 Fix AWS s3 status code 404 issue.](https://fynarfin.atlassian.net/browse/PHEE-648?atlOrigin=eyJpIjoiYmFjMGZmOTFlZTVhNGI0ZmI1ZmM4OTNmMzkzYzAwMGIiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> [PHEE-648] Fix AWS s3 status code 404 issue.

- src/test/java/org/mifos/integrationtest/cucumber/stepdef/BillPayStepDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/MockFlowTestDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/OperationsStepDef.java
- src/test/java/resources/billPay.feature
- src/test/java/resources/mockFlowTest.feature
- src/test/java/resources/operationsBatch.feature
> [phee-646] operations-batch-and-mft-testcases-fix

- .circleci/config.yml
- src/test/java/org/mifos/integrationtest/common/UniqueNumberGenerator.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/VoucherManagementStepDef.java
- src/test/java/resources/voucherManagementTest.feature
> [testFix] Voucher test fix

- src/test/java/org/mifos/integrationtest/cucumber/stepdef/MockFlowTestDef.java
- src/test/java/resources/batch.feature
- src/test/java/resources/batch_demo_csv/ph-ee-bulk-demo-6.csv
- src/test/java/resources/batch_demo_csv/ph-ee-bulk-demoErrorAsync-6.csv
> [PHEE-660] Batch TCs fix

- .circleci/config.yml
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/GenericStepDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/VoucherManagementStepDef.java
- src/test/java/resources/voucherManagementTest.feature
> [voucher-validation] Add voucher header validation

- src/main/java/org/mifos/integrationtest/config/BillPayConnectorConfig.java
- src/main/resources/application.yaml
- src/test/java/org/mifos/integrationtest/common/dto/BillStatusReqDTO.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/BillPayStepDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/ScenarioScopeState.java
- src/test/java/resources/billPay.feature
> [GOV-83New] Tcs for status API

- .circleci/config.yml
- src/test/java/org/mifos/integrationtest/common/dto/BillRTPReqDTO.java
- src/test/java/org/mifos/integrationtest/common/dto/PayerFSPDetail.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/BillPayStepDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/JWSStepDef.java
- src/test/java/resources/billPay.feature
[PHEE-665 Add validations in Bill-Pay service](https://fynarfin.atlassian.net/browse/PHEE-665?atlOrigin=eyJpIjoiM2Q0NmExOWRlMmQxNDYyYmI5YjNkNzc2OGEwMzllZTUiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> [phee-665] Fix bill pay test cases after adding validations

- src/test/java/org/mifos/integrationtest/cucumber/stepdef/BatchApiStepDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/VoucherManagementStepDef.java
- src/test/java/resources/identityMapperTest.feature
> [testfix] Increase await time

- src/test/java/org/mifos/integrationtest/cucumber/stepdef/BatchApiStepDef.java
> Fix for BD-019 test in ephemeral

- src/main/resources/application.yaml
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/ErrorCodeStepDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/GSMATransferStepDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/ScenarioScopeState.java
- src/test/java/resources/account.feature
- src/test/java/resources/batch_demo_csv/batchTransactionGsma.csv
> [PHEE-669] Tc for Account Status and Account Name APIs

- src/test/java/org/mifos/integrationtest/cucumber/stepdef/BatchApiStepDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/BillPayStepDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/BulkPaymentStepDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/GSMATransferStepDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/PayerFundTransferStepDef.java
- src/test/java/resources/batch.feature
- src/test/java/resources/batch_demo_csv/batchTransactionGsmaClosedLoop.csv
- src/test/java/resources/bulkPayment.feature
> [PHEE-675] Flaky TCs fix

- src/test/java/org/mifos/integrationtest/common/dto/operationsapp/BatchAndSubBatchSummaryResponse.java
- src/test/java/org/mifos/integrationtest/common/dto/operationsapp/PaymentBatchDetail.java
- src/test/java/org/mifos/integrationtest/common/dto/operationsapp/SubBatchSummary.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/BatchApiStepDef.java
> [PHEE-678] payment detail tc update

- src/main/java/org/mifos/integrationtest/config/OperationsAppConfig.java
- src/main/java/org/mifos/integrationtest/config/TenantConfig.java
- src/main/resources/application.yaml
- src/test/java/org/mifos/integrationtest/common/dto/operationsapp/ReportParameter.java
- src/test/java/org/mifos/integrationtest/common/dto/operationsapp/ReportRequestDTO.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/ScenarioScopeState.java
- src/test/java/resources/ReportManagementSteps.java
- src/test/java/resources/batch_demo_csv/report_api.feature
[PHEE-684 Reporting CRUD APIs](https://fynarfin.atlassian.net/browse/PHEE-684?atlOrigin=eyJpIjoiNTY5YTkxZjY4NmMxNGQwM2E1YmI5OGJkZTI0MTU2NzkiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> [PHEE-684]Integration testing for CRUD APIs.

- src/main/resources/application.yaml
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/GSMATransferStepDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/PayerFundTransferStepDef.java
- src/test/java/resources/batch_demo_csv/batchTransactionGsmaClosedLoop.csv
- src/test/java/resources/bulkPayment.feature
> Mifos co dev

- src/test/java/org/mifos/integrationtest/cucumber/stepdef/GSMATransferDef.java
- src/test/java/org/mifos/integrationtest/cucumber/stepdef/GSMATransferStepDef.java
- src/test/java/resources/gsmaTxn.feature
[PHEE-721 Fix /gsma/transcation API to work with different dfspids.](https://fynarfin.atlassian.net/browse/PHEE-721?atlOrigin=eyJpIjoiZTZkMjIwNGU1ODJkNDFjMWFjOTE3YzYwZDdlOTgzZjciLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> [PHEE-721] Fix /gsma/transcation API to work with different dfspids.
